sudo: false
language: java

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - mongodb-upstart
    packages:
      - mongodb-org-server
      - mongodb-org-shell

script: "./gradlew externalCiTest"

before_script:
- sleep 25

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  apt: true
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"